name: coingecko_dart
description: A Dart/Flutter Wrapper for the CoinGecko API (V3)
version: 0.1.0
homepage: https://github.com/TheAnimatrix/coingecko_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  quiver: ^3.0.1
  test: ^1.16.0
